import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';


export interface PeriodicElement {
  description : string;
  code: string;
  fee: number;
}

@Component({
  selector: 'app-insurance-setup',
  templateUrl: './insurance-setup.component.html',
  styleUrls: ['./insurance-setup.component.css']
})
export class InsuranceSetupComponent implements OnInit {

  constructor(private _formBuilder: FormBuilder) {}

  displayedColumns: string[] = ['code', 'description', 'fee'];
    //aggrid
    columnDefs = [
      {headerName: 'Code',  width: '80px', field: 'code', sortable: true,  filter: 'agTextColumnFilter', resizable: true },
      {headerName: 'Description', width: '600px', field: 'description',sortable: true,  filter: 'agTextColumnFilter',  resizable: true },
      {headerName: 'Price', field: 'fee', editable: true}
  ];
  
  rawData = [
    { code:'D0120', description: "periodic oral evaluation - established patient", fee: 884.63},
    { code:'D0140', description: "limited oral evaluation - problem focused", fee: 301.26},
    { code:'D0145', description: "oral evaluation for a patient under three years of age and counseling with primary caregiver", fee: 125.09},
    { code:'D0150', description: "comprehensive oral evaluation - new or established patient", fee: 667.95},
    { code:'D0160', description: "detailed and extensive oral evaluation - problem focused, by report", fee: 602.09},
    { code:'D0170', description: "re-evaluation - limited, problem focused (established patient; not post-operative visit)", fee: 851.10},
    { code:'D0171', description: "re-evaluation – post-operative office visit", fee: 204.04},
    { code:'D0180', description: "comprehensive periodontal evaluation - new or established patient", fee: 629.87},
    { code:'D0190', description: "screening of a patient", fee: 915.51},
    { code:'D0191', description: "assessment of a patient", fee: 234.56},
    { code:'D0210', description: "intraoral - complete series of radiographic images", fee: 739.56},
    { code:'D0220', description: "intraoral - periapical first radiographic image", fee: 208.90},
    { code:'D0230', description: "intraoral - periapical each additional radiographic image", fee: 325.34},
    { code:'D0240', description: "intraoral - occlusal radiographic image", fee: 165.86},
    { code:'D0250', description: "extra-oral – 2D projection radiographic image created using a stationary radiation source, and detector", fee: 493.78},
    { code:'D0251', description: "extra-oral posterior dental radiographic image", fee: 917.56},
    { code:'D0270', description: "bitewing - single radiographic image", fee: 944.45},
    { code:'D0272', description: "bitewings - two radiographic images", fee: 130.99},
    { code:'D0273', description: "bitewings - three radiographic images", fee: 990.76},
    { code:'D0274', description: "bitewings - four radiographic images", fee: 979.68},
    { code:'D0277', description: "vertical bitewings - 7 to 8 radiographic images", fee: 730.60},
    { code:'D0310', description: "sialography", fee: 380.49},
    { code:'D0320', description: "temporomandibular joint arthrogram, including injection", fee: 213.66},
    { code:'D0321', description: "other temporomandibular joint radiographic images, by report", fee: 680.64},
    { code:'D0322', description: "tomographic survey", fee: 841.23},
    { code:'D0330', description: "panoramic radiographic image", fee: 902.95},
    { code:'D0340', description: "2D cephalometric radiographic image – acquisition, measurement and analysis", fee: 934.78},
    { code:'D0350', description: "2D oral/facial photographic image obtained intra-orally or extra-orally", fee: 378.99},
    { code:'D0351', description: "3D photographic image", fee: 468.92},
    { code:'D0364', description: "cone beam CT capture and interpretation with limited field of view – less than one whole jaw", fee: 267.14},
    { code:'D0365', description: "cone beam CT capture and interpretation with field of view of one full dental arch – mandible", fee: 793.13},
    { code:'D0366', description: "cone beam CT capture and interpretation with field of view of one full dental arch – maxilla, with or without cranium", fee: 733.72},
    { code:'D0367', description: "cone beam CT capture and interpretation with field of view of both jaws; with or without cranium", fee: 504.94},
    { code:'D0368', description: "cone beam CT capture and interpretation for TMJ series including two or more exposures", fee: 592.49},
    { code:'D0369', description: "maxillofacial MRI capture and interpretation", fee: 801.64},
    { code:'D0370', description: "maxillofacial ultrasound capture and interpretation", fee: 776.79},
    { code:'D0371', description: "sialoendoscopy capture and interpretation", fee: 774.22},
    { code:'D0380', description: "cone beam CT image capture with limited field of view – less than one whole jaw", fee: 936.49},
    { code:'D0381', description: "cone beam CT image capture with field of view of one full dental arch – mandible", fee: 439.58},
    { code:'D0382', description: "cone beam CT image capture with field of view of one full dental arch – maxilla, with or without cranium", fee: 691.91},
    { code:'D0383', description: "cone beam CT image capture with field of view of both jaws; with or without cranium", fee: 386.22},
    { code:'D0384', description: "cone beam CT image capture for TMJ series including two or more exposures", fee: 71.42},
    { code:'D0385', description: "maxillofacial MRI image capture", fee: 865.82},
    { code:'D0386', description: "maxillofacial ultrasound image capture", fee: 548.23},
    { code:'D0391', description: "interpretation of diagnostic image by a practitioner not associated with capture of the image, including report", fee: 954.92},
    { code:'D0393', description: "treatment simulation using 3D image volume", fee: 964.48},
    { code:'D0394', description: "digital subtraction of two or more images or image volumes of the same modality", fee: 74.55},
    { code:'D0395', description: "fusion of two or more 3D image volumes of one or more modalities", fee: 781.56},
    { code:'D0411', description: "HbA1c in-office point of service testing", fee: 54.69},
    { code:'D0412', description: "blood glucose level test – in-office using a glucose meter", fee: 271.54},
    { code:'D0414', description: "laboratory processing of microbial specimen to include culture and sensitivity studies, preparation and transmission of written report", fee: 7.60},
    { code:'D0415', description: "collection of microorganisms for culture and sensitivity", fee: 916.03},
    { code:'D0416', description: "viral culture", fee: 299.89},
    { code:'D0417', description: "collection and preparation of saliva sample for laboratory diagnostic testing", fee: 809.01},
    { code:'D0418', description: "analysis of saliva sample", fee: 735.97},
    { code:'D0419', description: "assessment of salivary flow by measurement", fee: 875.36},
    { code:'D0422', description: "collection and preparation of genetic sample material for laboratory analysis and report", fee: 862.40},
    { code:'D0423', description: "genetic test for susceptibility to diseases – specimen analysis", fee: 277.00},
    { code:'D0425', description: "caries susceptibility tests", fee: 828.30},
    { code:'D0431', description: "adjunctive pre-diagnostic test that aids in detection of mucosal abnormalities including premalignant and malignant lesions, not to include cytology or biopsy procedures", fee: 245.79},
    { code:'D0460', description: "pulp vitality tests", fee: 74.56},
    { code:'D0470', description: "diagnostic casts", fee: 473.48},
    { code:'D0472', description: "accession of tissue, gross examination, preparation and transmission of written report", fee: 934.82},
    { code:'D0473', description: "accession of tissue, gross and microscopic examination, preparation and transmission of written report", fee: 21.50},
    { code:'D0474', description: "accession of tissue, gross and microscopic examination, including assessment of surgical margins for presence of disease, preparation and transmission of written report", fee: 4.07},
    { code:'D0475', description: "decalcification procedure", fee: 860.79},
    { code:'D0476', description: "special stains for microorganisms", fee: 432.96},
    { code:'D0477', description: "special stains, not for microorganisms", fee: 688.75},
    { code:'D0478', description: "immunohistochemical stains", fee: 533.02},
    { code:'D0479', description: "tissue in-situ hybridization, including interpretation", fee: 624.27},
    { code:'D0480', description: "accession of exfoliative cytologic smears, microscopic examination, preparation and transmission of written report", fee: 704.49},
    { code:'D0481', description: "electron microscopy", fee: 986.19},
    { code:'D0482', description: "direct immunofluorescence", fee: 524.92},
    { code:'D0483', description: "indirect immunofluorescence", fee: 297.46},
    { code:'D0484', description: "consultation on slides prepared elsewhere", fee: 243.47},
    { code:'D0485', description: "consultation, including preparation of slides from biopsy material supplied by referring source", fee: 316.60},
    { code:'D0486', description: "laboratory accession of transepithelial cytologic sample, microscopic examination, preparation and transmission of written report", fee: 121.71},
    { code:'D0502', description: "other oral pathology procedures, by report", fee: 619.10},
    { code:'D0600', description: "non-ionizing diagnostic procedure capable of quantifying,  monitoring, and recording changes in structure of enamel, dentin, and cementum", fee: 331.15},
    { code:'D0601', description: "caries risk assessment and documentation, with a finding of low risk", fee: 579.34},
    { code:'D0602', description: "caries risk assessment and documentation, with a finding of moderate risk", fee: 76.78},
    { code:'D0603', description: "caries risk assessment and documentation, with a finding of high risk", fee: 533.99},
    { code:'D0604', description: "antigen testing for a public health related pathogen, including coronavirus", fee: 455.63},
    { code:'D0605', description: "antibody testing for a public health related pathogen, including coronavirus", fee: 142.79},
    { code:'D0701', description: "panoramic radiographic image – image capture only", fee: 300.76},
    { code:'D0702', description: "2-D cephalometric radiographic image – image capture only", fee: 153.52},
    { code:'D0703', description: "2-D oral/facial photographic image obtained intra-orally or extra-orally – image capture only", fee: 3.27},
    { code:'D0704', description: "3-D photographic image – image capture only", fee: 782.70},
    { code:'D0705', description: "extra-oral posterior dental radiographic image – image capture only", fee: 473.46},
    { code:'D0706', description: "intraoral – occlusal radiographic image – image capture only", fee: 50.94},
    { code:'D0707', description: "intraoral – periapical radiographic image – image capture only", fee: 3.34},
    { code:'D0708', description: "intraoral – bitewing radiographic image – image capture only", fee: 674.92},
    { code:'D0709', description: "intraoral – complete series of radiographic images – image capture only", fee: 658.44},
    { code:'D0999', description: "unspecified diagnostic procedure, by report", fee: 482.24},
    { code:'D1110', description: "prophylaxis - adult", fee: 868.77},
    { code:'D1120', description: "prophylaxis - child", fee: 950.08},
    { code:'D1206', description: "topical application of fluoride varnish", fee: 345.87},
    { code:'D1208', description: "topical application of fluoride – excluding varnish", fee: 995.89},
    { code:'D1310', description: "nutritional counseling for control of dental disease", fee: 143.19},
    { code:'D1320', description: "tobacco counseling for the control and prevention of oral disease", fee: 892.73},
    { code:'D1321', description: "counseling for the control and prevention of adverse oral, behavioral, and systemic health effects associated with high-risk substance use", fee: 244.81},
    { code:'D1330', description: "oral hygiene instructions", fee: 422.61},
    { code:'D1351', description: "sealant - per tooth", fee: 237.94},
    { code:'D1352', description: "preventive resin restoration in a moderate to high caries risk patient – permanent tooth", fee: 599.25},
    { code:'D1353', description: "sealant repair – per tooth", fee: 448.02},
    { code:'D1354', description: "interim caries arresting medicament application – per tooth", fee: 421.20},
    { code:'D1355', description: "caries preventive medicament application – per tooth", fee: 22.82},
    { code:'D1510', description: "space maintainer - fixed, unilateral – per quadrant", fee: 796.20},
    { code:'D1516', description: "space maintainer - fixed - bilateral, maxillary", fee: 300.10},
    { code:'D1517', description: "space maintainer - fixed - bilateral, mandibular", fee: 597.18},
    { code:'D1520', description: "space maintainer - removable, unilateral - per quadrant", fee: 920.42},
    { code:'D1526', description: "space maintainer - removable - bilateral, maxillary", fee: 564.92},
    { code:'D1527', description: "space maintainer - removable - bilateral, mandibular", fee: 414.32},
    { code:'D1551', description: "re-cement or re-bond bilateral space maintainer - maxillary", fee: 708.03},
    { code:'D1552', description: "re-cement or re-bond bilateral space maintainer - mandibular", fee: 846.13},
    { code:'D1553', description: "re-cement or re-bond unilateral space maintainer - per quadrant", fee: 918.35},
    { code:'D1556', description: "removal of fixed unilateral space maintainer - per quadrant", fee: 803.75},
    { code:'D1557', description: "removal of fixed bilateral space maintainer - maxillary", fee: 622.26},
    { code:'D1558', description: "removal of fixed bilateral space maintainer - mandibular", fee: 934.66},
    { code:'D1575', description: "distal shoe space maintainer - fixed, unilateral - per quadrant", fee: 532.42},
    { code:'D1999', description: "unspecified preventive procedure, by report", fee: 19.27},
    { code:'D2140', description: "amalgam - one surface, primary or permanent", fee: 508.85},
    { code:'D2150', description: "amalgam - two surfaces, primary or permanent", fee: 498.93},
    { code:'D2160', description: "amalgam - three surfaces, primary or permanent", fee: 447.19},
    { code:'D2161', description: "amalgam - four or more surfaces, primary or permanent", fee: 519.88},
    { code:'D2330', description: "resin-based composite - one surface, anterior", fee: 199.79},
    { code:'D2331', description: "resin-based composite - two surfaces, anterior", fee: 77.92},
    { code:'D2332', description: "resin-based composite - three surfaces, anterior", fee: 221.62},
    { code:'D2335', description: "resin-based composite - four or more surfaces or involving incisal angle (anterior)", fee: 240.13},
    { code:'D2390', description: "resin-based composite crown, anterior", fee: 790.23},
    { code:'D2391', description: "resin-based composite - one surface, posterior", fee: 747.99},
    { code:'D2392', description: "resin-based composite - two surfaces, posterior", fee: 851.42},
    { code:'D2393', description: "resin-based composite - three surfaces, posterior", fee: 464.88},
    { code:'D2394', description: "resin-based composite - four or more surfaces, posterior", fee: 319.17},
    { code:'D2410', description: "gold foil - one surface", fee: 95.26},
    { code:'D2420', description: "gold foil - two surfaces", fee: 740.50},
    { code:'D2430', description: "gold foil - three surfaces", fee: 673.41},
    { code:'D2510', description: "inlay - metallic - one surface", fee: 808.18},
    { code:'D2520', description: "inlay - metallic - two surfaces", fee: 377.00},
    { code:'D2530', description: "inlay - metallic - three or more surfaces", fee: 154.38},
    { code:'D2542', description: "onlay - metallic - two surfaces", fee: 972.98},
    { code:'D2543', description: "onlay - metallic - three surfaces", fee: 26.50},
    { code:'D2544', description: "onlay - metallic - four or more surfaces", fee: 435.78},
    { code:'D2610', description: "inlay - porcelain/ceramic - one surface", fee: 878.09},
    { code:'D2620', description: "inlay - porcelain/ceramic - two surfaces", fee: 105.98},
    { code:'D2630', description: "inlay - porcelain/ceramic - three or more surfaces", fee: 97.88},
    { code:'D2642', description: "onlay - porcelain/ceramic - two surfaces", fee: 872.63},
    { code:'D2643', description: "onlay - porcelain/ceramic - three surfaces", fee: 250.77},
    { code:'D2644', description: "onlay - porcelain/ceramic - four or more surfaces", fee: 785.62},
    { code:'D2650', description: "inlay - resin-based composite - one surface", fee: 467.89},
    { code:'D2651', description: "inlay - resin-based composite - two surfaces", fee: 834.28},
    { code:'D2652', description: "inlay - resin-based composite - three or more surfaces", fee: 356.18},
    { code:'D2662', description: "onlay - resin-based composite - two surfaces", fee: 291.56},
    { code:'D2663', description: "onlay - resin-based composite - three surfaces", fee: 809.92},
    { code:'D2664', description: "onlay - resin-based composite - four or more surfaces", fee: 523.94},
    { code:'D2710', description: "crown - resin-based composite (indirect)", fee: 910.70},
    { code:'D2712', description: "crown - ¾ resin-based composite (indirect)", fee: 840.23},
    { code:'D2720', description: "crown - resin with high noble metal", fee: 164.09},
    { code:'D2721', description: "crown - resin with predominantly base metal", fee: 206.82},
    { code:'D2722', description: "crown - resin with noble metal", fee: 309.31},
    { code:'D2740', description: "crown - porcelain/ceramic", fee: 233.38},
    { code:'D2750', description: "crown - porcelain fused to high noble metal", fee: 975.07},
    { code:'D2751', description: "crown - porcelain fused to predominantly base metal", fee: 48.50},
    { code:'D2752', description: "crown - porcelain fused to noble metal", fee: 365.59},
    { code:'D2753', description: "crown - porcelain fused to titanium and titanium alloys", fee: 684.45},
    { code:'D2780', description: "crown - 3/4 cast high noble metal", fee: 723.46},
    { code:'D2781', description: "crown - 3/4 cast predominantly base metal", fee: 598.18},
    { code:'D2782', description: "crown - 3/4 cast noble metal", fee: 512.69},
    { code:'D2783', description: "crown - 3/4 porcelain/ceramic", fee: 523.73},
    { code:'D2790', description: "crown - full cast high noble metal", fee: 529.65},
    { code:'D2791', description: "crown - full cast predominantly base metal", fee: 108.48},
    { code:'D2792', description: "crown - full cast noble metal", fee: 620.45},
    { code:'D2794', description: "crown - titanium and titanium alloys", fee: 691.31},
    { code:'D2799', description: "provisional crown– further treatment or completion of diagnosis necessary prior to final impression", fee: 450.18},
    { code:'D2910', description: "re-cement or re-bond inlay, onlay, veneer or partial coverage restoration", fee: 169.85},
    { code:'D2915', description: "re-cement or re-bond indirectly fabricated or prefabricated post and core", fee: 127.47},
    { code:'D2920', description: "re-cement or re-bond crown", fee: 541.36},
    { code:'D2921', description: "reattachment of tooth fragment, incisal edge or cusp", fee: 183.40},
    { code:'D2928', description: "prefabricated porcelain/ceramic crown – permanent tooth", fee: 329.90},
    { code:'D2929', description: "prefabricated porcelain/ceramic crown – primary tooth", fee: 887.07},
    { code:'D2930', description: "prefabricated stainless steel crown - primary tooth", fee: 501.37},
    { code:'D2931', description: "prefabricated stainless steel crown - permanent tooth", fee: 554.87},
    { code:'D2932', description: "prefabricated resin crown", fee: 466.49},
    { code:'D2933', description: "prefabricated stainless steel crown with resin window", fee: 982.98},
    { code:'D2934', description: "prefabricated esthetic coated stainless steel crown - primary tooth", fee: 557.23},
    { code:'D2940', description: "protective restoration", fee: 462.09},
    { code:'D2941', description: "interim therapeutic restoration – primary dentition", fee: 688.51},
    { code:'D2949', description: "restorative foundation for an indirect restoration", fee: 782.63},
    { code:'D2950', description: "core buildup, including any pins when required", fee: 367.46},
    { code:'D2951', description: "pin retention - per tooth, in addition to restoration", fee: 924.58},
    { code:'D2952', description: "post and core in addition to crown, indirectly fabricated", fee: 449.36},
    { code:'D2953', description: "each additional indirectly fabricated post - same tooth", fee: 665.42},
    { code:'D2954', description: "prefabricated post and core in addition to crown", fee: 49.72},
    { code:'D2955', description: "post removal", fee: 506.66},
    { code:'D2957', description: "each additional prefabricated post - same tooth", fee: 375.34},
    { code:'D2960', description: "labial veneer (resin laminate) - direct", fee: 188.31},
    { code:'D2961', description: "labial veneer (resin laminate) - indirect", fee: 327.86},
    { code:'D2962', description: "labial veneer (porcelain laminate) - indirect", fee: 659.23},
    { code:'D2971', description: "additional procedures to construct new crown under existing partial denture framework", fee: 35.00},
    { code:'D2975', description: "coping", fee: 932.45},
    { code:'D2980', description: "crown repair necessitated by restorative material failure", fee: 779.72},
    { code:'D2981', description: "inlay repair necessitated by restorative material failure", fee: 461.14},
    { code:'D2982', description: "onlay repair necessitated by restorative material failure", fee: 505.42},
    { code:'D2983', description: "veneer repair necessitated by restorative material failure", fee: 912.41},
    { code:'D2990', description: "resin infiltration of incipient smooth surface lesions", fee: 383.71},
    { code:'D2999', description: "unspecified restorative procedure, by report", fee: 831.43},
    { code:'D3110', description: "pulp cap - direct (excluding final restoration)", fee: 127.23},
    { code:'D3120', description: "pulp cap - indirect (excluding final restoration)", fee: 223.44},
    { code:'D3220', description: "therapeutic pulpotomy (excluding final restoration) - removal of pulp coronal to the dentinocemental junction and application of medicament", fee: 426.77},
    { code:'D3221', description: "pulpal debridement, primary and permanent teeth", fee: 531.23},
    { code:'D3222', description: "partial pulpotomy for apexogenesis - permanent tooth with incomplete root development", fee: 282.86},
    { code:'D3230', description: "pulpal therapy (resorbable filling) - anterior, primary tooth (excluding final restoration)", fee: 552.46},
    { code:'D3240', description: "pulpal therapy (resorbable filling) - posterior, primary tooth (excluding final restoration)", fee: 106.40},
    { code:'D3310', description: "endodontic therapy, anterior tooth (excluding final restoration)", fee: 176.84},
    { code:'D3320', description: "endodontic therapy, premolar tooth (excluding final restoration)", fee: 381.05},
    { code:'D3330', description: "endodontic therapy, molar tooth (excluding final restoration)", fee: 284.70},
    { code:'D3331', description: "treatment of root canal obstruction; non-surgical access", fee: 836.68},
    { code:'D3332', description: "incomplete endodontic therapy; inoperable, unrestorable or fractured tooth", fee: 45.67},
    { code:'D3333', description: "internal root repair of perforation defects", fee: 485.47},
    { code:'D3346', description: "retreatment of previous root canal therapy - anterior", fee: 200.98},
    { code:'D3347', description: "retreatment of previous root canal therapy - premolar", fee: 350.71},
    { code:'D3348', description: "retreatment of previous root canal therapy - molar", fee: 672.03},
    { code:'D3351', description: "apexification/recalcification – initial visit (apical closure/calcific repair of perforations, root resorption, etc.)", fee: 186.48},
    { code:'D3352', description: "apexification/recalcification – interim medication replacement", fee: 179.25},
    { code:'D3353', description: "apexification/recalcification - final visit (includes completed root canal therapy - apical closure/calcific repair of perforations, root resorption, etc.)", fee: 181.64},
    { code:'D3355', description: "pulpal regeneration - initial visit", fee: 102.32},
    { code:'D3356', description: "pulpal regeneration - interim medication replacement", fee: 382.46},
    { code:'D3357', description: "pulpal regeneration - completion of treatment", fee: 889.24},
    { code:'D3410', description: "apicoectomy - anterior", fee: 999.55},
    { code:'D3421', description: "apicoectomy - premolar (first root)", fee: 206.89},
    { code:'D3425', description: "apicoectomy - molar (first root)", fee: 610.76},
    { code:'D3426', description: "apicoectomy (each additional root)", fee: 200.78},
    { code:'D3427', description: "periradicular surgery without apicoectomy", fee: 583.52},
    { code:'D3428', description: "bone graft in conjunction with periradicular surgery – per tooth, single site", fee: 631.13},
    { code:'D3429', description: "bone graft in conjunction with periradicular surgery – each additional contiguous tooth in the same surgical site", fee: 448.19},
    { code:'D3430', description: "retrograde filling - per root", fee: 913.69},
    { code:'D3431', description: "biologic materials to aid in soft and osseous tissue regeneration in conjunction with periradicular surgery", fee: 916.00},
    { code:'D3432', description: "guided tissue regeneration, resorbable barrier, per site, in conjunction with periradicular surgery", fee: 808.55},
    { code:'D3450', description: "root amputation - per root", fee: 287.10},
    { code:'D3460', description: "endodontic endosseous implant", fee: 461.25},
    { code:'D3470', description: "intentional re-implantation (including necessary splinting)", fee: 1.09},
    { code:'D3471', description: "surgical repair of root resorption - anterior", fee: 955.92},
    { code:'D3472', description: "surgical repair of root resorption – premolar", fee: 485.52},
    { code:'D3473', description: "surgical repair of root resorption – molar", fee: 439.61},
    { code:'D3501', description: "surgical exposure of root surface without apicoectomy or repair of root resorption – anterior", fee: 528.50},
    { code:'D3502', description: "surgical exposure of root surface without apicoectomy or repair of root resorption – premolar", fee: 124.04},
    { code:'D3503', description: "surgical exposure of root surface without apicoectomy or repair of root resorption – molar", fee: 488.36},
    { code:'D3910', description: "surgical procedure for isolation of tooth with rubber dam", fee: 171.59},
    { code:'D3920', description: "hemisection (including any root removal), not including root canal therapy", fee: 432.12},
    { code:'D3950', description: "canal preparation and fitting of preformed dowel or post", fee: 186.96},
    { code:'D3999', description: "unspecified endodontic procedure, by report", fee: 21.83},
    { code:'D4210', description: "gingivectomy or gingivoplasty - four or more contiguous teeth or tooth bounded spaces per quadrant", fee: 26.35},
    { code:'D4211', description: "gingivectomy or gingivoplasty - one to three contiguous teeth or tooth bounded spaces per quadrant", fee: 724.89},
    { code:'D4212', description: "gingivectomy or gingivoplasty to allow access for restorative procedure, per tooth", fee: 118.45},
    { code:'D4230', description: "anatomical crown exposure – four or more contiguous teeth or tooth bounded spaces per quadrant", fee: 873.83},
    { code:'D4231', description: "anatomical crown exposure – one to three teeth or tooth bounded spaces per quadrant", fee: 885.19},
    { code:'D4240', description: "gingival flap procedure, including root planing - four or more contiguous teeth or tooth bounded spaces per quadrant", fee: 730.87},
    { code:'D4241', description: "gingival flap procedure, including root planing - one to three contiguous teeth or tooth bounded spaces per quadrant", fee: 26.60},
    { code:'D4245', description: "apically positioned flap", fee: 91.19},
    { code:'D4249', description: "clinical crown lengthening – hard tissue", fee: 968.87},
    { code:'D4260', description: "osseous surgery (including elevation of a full thickness flap and closure) – four or more contiguous teeth or tooth bounded spaces per quadrant", fee: 981.18},
    { code:'D4261', description: "osseous surgery (including elevation of a full thickness flap and closure) – one to three contiguous teeth or tooth bounded spaces per quadrant", fee: 195.81},
    { code:'D4263', description: "bone replacement graft – retained natural tooth – first site in quadrant", fee: 647.50},
    { code:'D4264', description: "bone replacement graft – retained natural tooth – each additional site in quadrant", fee: 223.58},
    { code:'D4265', description: "biologic materials to aid in soft and osseous tissue regeneration", fee: 592.00},
    { code:'D4266', description: "guided tissue regeneration - resorbable barrier, per site", fee: 819.70},
    { code:'D4267', description: "guided tissue regeneration - nonresorbable barrier, per site (includes membrane removal)", fee: 765.78},
    { code:'D4268', description: "surgical revision procedure, per tooth", fee: 599.97},
    { code:'D4270', description: "pedicle soft tissue graft procedure", fee: 900.79},
    { code:'D4273', description: "autogenous connective tissue graft procedure (including donor and recipient surgical sites) first tooth, implant, or edentulous tooth position in graft", fee: 199.73},
    { code:'D4274', description: "mesial/distal wedge procedure, single tooth (when not performed in conjunction with surgical procedures in the same anatomical area)", fee: 116.01},
    { code:'D4275', description: "non-autogenous connective tissue graft (including recipient site and donor material) first tooth, implant, or edentulous tooth position in graft", fee: 853.94},
    { code:'D4276', description: "combined connective tissue and double pedicle graft, per tooth", fee: 501.57},
    { code:'D4277', description: "free soft tissue graft procedure (including recipient and donor surgical sites) first tooth, implant or edentulous tooth position in graft", fee: 931.07},
    { code:'D4278', description: "free soft tissue graft procedure (including recipient and donor surgical sites) each additional contiguous tooth, implant or edentulous tooth position in same graft site", fee: 49.96},
    { code:'D4283', description: "autogenous connective tissue graft procedure (including donor and recipient surgical sites) – each additional contiguous tooth, implant or edentulous tooth position in same graft site", fee: 947.90},
    { code:'D4285', description: "non-autogenous connective tissue graft procedure (including recipient surgical site and donor material) – each additional contiguous tooth, implant or edentulous tooth position in same", fee: 589.94},
    { code:'D4320', description: "provisional splinting - intracoronal", fee: 0.64},
    { code:'D4321', description: "provisional splinting - extracoronal", fee: 884.63},
    { code:'D4341', description: "periodontal scaling and root planing - four or more teeth per quadrant", fee: 737.80},
    { code:'D4342', description: "periodontal scaling and root planing - one to three teeth per quadrant", fee: 705.91},
    { code:'D4346', description: "scaling in presence of generalized moderate or severe gingival inflammation – full mouth, after oral evaluation", fee: 781.94},
    { code:'D4355', description: "full mouth debridement to enable a comprehensive oral evaluation and diagnosis on a subsequent visit", fee: 0.16},
    { code:'D4381', description: "localized delivery of antimicrobial agents via a controlled release vehicle into diseased crevicular tissue, per tooth", fee: 393.66},
    { code:'D4910', description: "periodontal maintenance", fee: 545.19},
    { code:'D4920', description: "unscheduled dressing change (by someone other than treating dentist or their staff)", fee: 626.94},
    { code:'D4921', description: "gingival irrigation – per quadrant", fee: 179.48},
    { code:'D4999', description: "unspecified periodontal procedure, by report", fee: 920.69},
    { code:'D5110', description: "complete denture - maxillary", fee: 499.12},
    { code:'D5120', description: "complete denture - mandibular", fee: 127.45},
    { code:'D5130', description: "immediate denture - maxillary", fee: 184.10},
    { code:'D5140', description: "immediate denture - mandibular", fee: 222.79},
    { code:'D5211', description: "maxillary partial denture – resin base (including, retentive/clasping materials, rests, and teeth)", fee: 978.68},
    { code:'D5212', description: "mandibular partial denture – resin base (including, retentive/clasping materials, rests, and teeth)", fee: 146.81},
    { code:'D5213', description: "maxillary partial denture - cast metal framework with resin denture bases (including retentive/clasping materials, rests and teeth)", fee: 34.39},
    { code:'D5214', description: "mandibular partial denture - cast metal framework with resin denture bases (including retentive/clasping materials, rests and teeth)", fee: 382.12},
    { code:'D5221', description: "immediate maxillary partial denture - resin base (including retentive/clasping materials, rests and teeth)", fee: 380.08},
    { code:'D5222', description: "immediate mandibular partial denture - resin base (including retentive/clasping materials, rests and teeth)", fee: 407.10},
    { code:'D5223', description: "immediate maxillary partial denture - cast metal framework with resin denture bases (including retentive/clasping materials, rests and teeth)", fee: 842.26},
    { code:'D5224', description: "immediate mandibular partial denture - cast metal framework with resin denture bases (including retentive/clasping materials, rests and teeth)", fee: 215.89},
    { code:'D5225', description: "maxillary partial denture - flexible base (including retentive/clasping materials, rests, and teeth)", fee: 757.04},
    { code:'D5226', description: "mandibular partial denture - flexible base (including retentive/clasping materials, rests, and teeth)", fee: 757.97},
    { code:'D5282', description: "removable unilateral partial denture – one piece cast metal (including retentive/clasping materials, rests, and teeth), maxillary", fee: 330.49},
    { code:'D5283', description: "removable unilateral partial denture – one piece cast metal (including rententive/clasping materias, rests, and teeth), mandibular", fee: 715.37},
    { code:'D5284', description: "removable unilateral partial denture – one piece flexible base (including retentive/clasping materials, rests, and teeth) – per quadrant", fee: 879.64},
    { code:'D5286', description: "removable unilateral partial denture – one piece resin (including retentive/clasping materials, rests, and teeth) – per quadrant", fee: 250.45},
    { code:'D5410', description: "adjust complete denture - maxillary", fee: 365.25},
    { code:'D5411', description: "adjust complete denture - mandibular", fee: 672.68},
    { code:'D5421', description: "adjust partial denture - maxillary", fee: 379.58},
    { code:'D5422', description: "adjust partial denture - mandibular", fee: 792.15},
    { code:'D5511', description: "repair broken complete denture base, mandibular", fee: 927.05},
    { code:'D5512', description: "repair broken complete denture base, maxillary", fee: 656.86},
    { code:'D5520', description: "replace missing or broken teeth - complete denture (each tooth)", fee: 108.86},
    { code:'D5611', description: "repair resin partial denture base, mandibular", fee: 469.84},
    { code:'D5612', description: "repair resin partial denture base, maxillary", fee: 950.13},
    { code:'D5621', description: "repair cast partial framework, mandibular", fee: 513.95},
    { code:'D5622', description: "repair cast partial framework, maxillary", fee: 671.73},
    { code:'D5630', description: "repair or replace broken retentive clasping materials – per tooth", fee: 591.61},
    { code:'D5640', description: "replace broken teeth - per tooth", fee: 371.62},
    { code:'D5650', description: "add tooth to existing partial denture", fee: 734.32},
    { code:'D5660', description: "add clasp to existing partial denture - per tooth", fee: 328.99},
    { code:'D5670', description: "replace all teeth and acrylic on cast metal framework (maxillary)", fee: 122.26},
    { code:'D5671', description: "replace all teeth and acrylic on cast metal framework (mandibular)", fee: 548.99},
    { code:'D5710', description: "rebase complete maxillary denture", fee: 355.93},
    { code:'D5711', description: "rebase complete mandibular denture", fee: 119.33},
    { code:'D5720', description: "rebase maxillary partial denture", fee: 464.46},
    { code:'D5721', description: "rebase mandibular partial denture", fee: 927.95},
    { code:'D5730', description: "reline complete maxillary denture (direct)", fee: 553.57},
    { code:'D5731', description: "reline complete mandibular denture (direct)", fee: 94.05},
    { code:'D5740', description: "reline maxillary partial denture (direct)", fee: 472.44},
    { code:'D5741', description: "reline mandibular partial denture (direct)", fee: 473.19},
    { code:'D5750', description: "reline complete maxillary denture (indirect)", fee: 701.79},
    { code:'D5751', description: "reline complete mandibular denture (indirect)", fee: 19.63},
    { code:'D5760', description: "reline maxillary partial denture (indirect)", fee: 175.95},
    { code:'D5761', description: "reline mandibular partial denture (indirect)", fee: 909.80},
    { code:'D5810', description: "interim complete denture (maxillary)", fee: 493.28},
    { code:'D5811', description: "interim complete denture (mandibular)", fee: 766.75},
    { code:'D5820', description: "interim partial denture (including retentive/clasping materials, rests, and teeth), maxillary", fee: 939.17},
    { code:'D5821', description: "interim partial denture (including retentive/clasping materials, rests, and teeth), mandibular", fee: 266.41},
    { code:'D5850', description: "tissue conditioning, maxillary", fee: 644.54},
    { code:'D5851', description: "tissue conditioning, mandibular", fee: 874.88},
    { code:'D5862', description: "precision attachment, by report", fee: 682.80},
    { code:'D5863', description: "overdenture – complete maxillary", fee: 559.03},
    { code:'D5864', description: "overdenture – partial maxillary", fee: 827.22},
    { code:'D5865', description: "overdenture – complete mandibular", fee: 458.57},
    { code:'D5866', description: "overdenture – partial mandibular", fee: 356.80},
    { code:'D5867', description: "replacement of replaceable part of semi-precision or precision attachment (male or female component)", fee: 709.85},
    { code:'D5875', description: "modification of removable prosthesis following implant surgery", fee: 726.08},
    { code:'D5876', description: "add metal substructure to acrylic full denture (per arch)", fee: 704.07},
    { code:'D5899', description: "unspecified removable prosthodontic procedure, by report", fee: 67.46},
    { code:'D5911', description: "facial moulage (sectional)", fee: 956.26},
    { code:'D5912', description: "facial moulage (complete)", fee: 543.69},
    { code:'D5913', description: "nasal prosthesis", fee: 694.74},
    { code:'D5914', description: "auricular prosthesis", fee: 134.09},
    { code:'D5915', description: "orbital prosthesis", fee: 72.82},
    { code:'D5916', description: "ocular prosthesis", fee: 846.85},
    { code:'D5919', description: "facial prosthesis", fee: 198.80},
    { code:'D5922', description: "nasal septal prosthesis", fee: 879.49},
    { code:'D5923', description: "ocular prosthesis, interim", fee: 702.29},
    { code:'D5924', description: "cranial prosthesis", fee: 381.53},
    { code:'D5925', description: "facial augmentation implant prosthesis", fee: 354.88},
    { code:'D5926', description: "nasal prosthesis, replacement", fee: 142.32},
    { code:'D5927', description: "auricular prosthesis, replacement", fee: 972.13},
    { code:'D5928', description: "orbital prosthesis, replacement", fee: 370.54},
    { code:'D5929', description: "facial prosthesis, replacement", fee: 898.95},
    { code:'D5931', description: "obturator prosthesis, surgical", fee: 340.94},
    { code:'D5932', description: "obturator prosthesis, definitive", fee: 358.62},
    { code:'D5933', description: "obturator prosthesis, modification", fee: 852.21},
    { code:'D5934', description: "mandibular resection prosthesis with guide flange", fee: 690.17},
    { code:'D5935', description: "mandibular resection prosthesis without guide flange", fee: 414.76},
    { code:'D5936', description: "obturator prosthesis, interim", fee: 453.34},
    { code:'D5937', description: "trismus appliance (not for TMD treatment)", fee: 818.55},
    { code:'D5951', description: "feeding aid", fee: 814.02},
    { code:'D5952', description: "speech aid prosthesis, pediatric", fee: 122.92},
    { code:'D5953', description: "speech aid prosthesis, adult", fee: 885.38},
    { code:'D5954', description: "palatal augmentation prosthesis", fee: 267.73},
    { code:'D5955', description: "palatal lift prosthesis, definitive", fee: 467.73},
    { code:'D5958', description: "palatal lift prosthesis, interim", fee: 989.51},
    { code:'D5959', description: "palatal lift prosthesis, modification", fee: 157.39},
    { code:'D5960', description: "speech aid prosthesis, modification", fee: 798.58},
    { code:'D5982', description: "surgical stent", fee: 165.81},
    { code:'D5983', description: "radiation carrier", fee: 650.22},
    { code:'D5984', description: "radiation shield", fee: 564.91},
    { code:'D5985', description: "radiation cone locator", fee: 43.56},
    { code:'D5986', description: "fluoride gel carrier", fee: 543.13},
    { code:'D5987', description: "commissure splint", fee: 477.75},
    { code:'D5988', description: "surgical splint", fee: 685.67},
    { code:'D5991', description: "vesiculobullous disease medicament carrier", fee: 61.95},
    { code:'D5992', description: "adjust maxillofacial prosthetic appliance, by report", fee: 178.28},
    { code:'D5993', description: "maintenance and cleaning of a maxillofacial prosthesis (extra- or intra-oral) other than required adjustments, by report", fee: 141.17},
    { code:'D5994', description: "periodontal medicament carrier with peripheral seal – laboratory processed", fee: 149.21},
    { code:'D5995', description: "periodontal medicament carrier with peripheral seal – laboratory processed – maxillary", fee: 796.48},
    { code:'D5996', description: "periodontal medicament carrier with peripheral seal – laboratory processed – mandibular", fee: 411.58},
    { code:'D5999', description: "unspecified maxillofacial prosthesis, by report", fee: 189.41},
    { code:'D6010', description: "surgical placement of implant body: endosteal implant", fee: 527.02},
    { code:'D6011', description: "surgical access to an implant body (second stage implant surgery)", fee: 834.22},
    { code:'D6012', description: "surgical placement of interim implant body for transitional prosthesis: endosteal implant", fee: 90.45},
    { code:'D6013', description: "surgical placement of mini implant", fee: 839.64},
    { code:'D6040', description: "surgical placement: eposteal implant", fee: 219.71},
    { code:'D6050', description: "surgical placement: transosteal implant", fee: 6.60},
    { code:'D6051', description: "interim abutment", fee: 538.83},
    { code:'D6052', description: "semi-precision attachment abutment", fee: 898.32},
    { code:'D6055', description: "connecting bar – implant supported or abutment supported", fee: 159.78},
    { code:'D6056', description: "prefabricated abutment – includes modification and placement", fee: 813.53},
    { code:'D6057', description: "custom fabricated abutment – includes placement", fee: 817.94},
    { code:'D6058', description: "abutment supported porcelain/ceramic crown", fee: 146.33},
    { code:'D6059', description: "abutment supported porcelain fused to metal crown (high noble metal)", fee: 997.50},
    { code:'D6060', description: "abutment supported porcelain fused to metal crown (predominantly base metal)", fee: 263.16},
    { code:'D6061', description: "abutment supported porcelain fused to metal crown (noble metal)", fee: 522.46},
    { code:'D6062', description: "abutment supported cast metal crown (high noble metal)", fee: 578.81},
    { code:'D6063', description: "abutment supported cast metal crown (predominantly base metal)", fee: 192.21},
    { code:'D6064', description: "abutment supported cast metal crown (noble metal)", fee: 481.30},
    { code:'D6065', description: "implant supported porcelain/ceramic crown", fee: 939.13},
    { code:'D6066', description: "implant supported crown - porcelain fused to high noble alloys", fee: 606.29},
    { code:'D6067', description: "implant supported crown - high noble alloys", fee: 92.28},
    { code:'D6068', description: "abutment supported retainer for porcelain/ceramic FPD", fee: 363.76},
    { code:'D6069', description: "abutment supported retainer for porcelain fused to metal FPD (high noble metal)", fee: 384.21},
    { code:'D6070', description: "abutment supported retainer for porcelain fused to metal FPD (predominantly base metal)", fee: 695.93},
    { code:'D6071', description: "abutment supported retainer for porcelain fused to metal FPD (noble metal)", fee: 654.67},
    { code:'D6072', description: "abutment supported retainer for cast metal FPD (high noble metal)", fee: 619.78},
    { code:'D6073', description: "abutment supported retainer for cast metal FPD (predominantly base metal)", fee: 931.49},
    { code:'D6074', description: "abutment supported retainer for cast metal FPD (noble metal)", fee: 959.71},
    { code:'D6075', description: "implant supported retainer for ceramic FPD", fee: 928.48},
    { code:'D6076', description: "implant supported retainer for FPD - porcelain fused to high noble alloys", fee: 786.36},
    { code:'D6077', description: "implant supported retainer for metal FPD - high noble alloys", fee: 544.44},
    { code:'D6080', description: "implant maintenance procedures when prostheses are removed and reinserted, including cleansing of prostheses and abutments", fee: 881.16},
    { code:'D6081', description: "scaling and debridement in the presence of inflammation or mucositis of a single implant, including cleaning of the implant surfaces, without flap entry and closure", fee: 806.68},
    { code:'D6082', description: "implant supported crown - porcelain fused to predominantly base alloys", fee: 180.93},
    { code:'D6083', description: "implant supported crown - porcelain fused to noble alloys", fee: 834.20},
    { code:'D6084', description: "implant supported crown - porcelain fused to titanium and titanium alloys", fee: 713.09},
    { code:'D6085', description: "provisional implant crown", fee: 836.67},
    { code:'D6086', description: "implant supported crown - predominantly base alloys", fee: 303.71},
    { code:'D6087', description: "implant supported crown - noble alloys", fee: 279.15},
    { code:'D6088', description: "implant supported crown - titanium and titanium alloys", fee: 75.68},
    { code:'D6090', description: "repair implant supported prosthesis, by report", fee: 72.22},
    { code:'D6091', description: "replacement of replaceable part of semi-precision or precision attachment (male or female component) of implant/abutment supported prosthesis, per attachment", fee: 901.31},
    { code:'D6092', description: "re-cement or re-bond implant/abutment supported crown", fee: 762.43},
    { code:'D6093', description: "re-cement or re-bond implant/abutment supported fixed partial denture", fee: 937.72},
    { code:'D6094', description: "abutment supported crown - titanium and titanium alloys", fee: 48.56},
    { code:'D6095', description: "repair implant abutment, by report", fee: 759.72},
    { code:'D6096', description: "remove broken implant retaining screw", fee: 710.60},
    { code:'D6097', description: "abutment supported crown - porcelain fused to titanium and titanium alloys", fee: 473.37},
    { code:'D6098', description: "implant supported retainer - porcelain fused to predominantly base alloys", fee: 966.57},
    { code:'D6099', description: "implant supported retainer for FPD - porcelain fused to noble alloys", fee: 307.27},
    { code:'D6100', description: "implant removal, by report", fee: 949.40},
    { code:'D6101', description: "debridement of a peri-implant defect or defects surrounding a single implant, and surface cleaning of the exposed implant surfaces, including flap entry and closure", fee: 252.58},
    { code:'D6102', description: "debridement and osseous contouring of a peri-implant defect or defects surrounding a single implant and includes surface cleaning of the exposed implant surfaces, including flap entry", fee: 83.98},
    { code:'D6103', description: "bone graft for repair of peri-implant defect – does not include flap entry and closure", fee: 277.27},
    { code:'D6104', description: "bone graft at time of implant placement", fee: 632.19},
    { code:'D6110', description: "implant /abutment supported removable denture for edentulous arch – maxillary", fee: 845.37},
    { code:'D6111', description: "implant /abutment supported removable denture for edentulous arch – mandibular", fee: 127.95},
    { code:'D6112', description: "implant /abutment supported removable denture for partially edentulous arch – maxillary", fee: 5.25},
    { code:'D6113', description: "implant /abutment supported removable denture for partially edentulous arch – mandibular", fee: 241.80},
    { code:'D6114', description: "implant /abutment supported fixed denture for edentulous arch – maxillary", fee: 198.62},
    { code:'D6115', description: "implant /abutment supported fixed denture for edentulous arch – mandibular", fee: 268.00},
    { code:'D6116', description: "implant /abutment supported fixed denture for partially edentulous arch – maxillary", fee: 417.01},
    { code:'D6117', description: "implant /abutment supported fixed denture for partially edentulous arch – mandibular", fee: 718.46},
    { code:'D6118', description: "implant/abutment supported interim fixed denture for edentulous arch – mandibular", fee: 78.35},
    { code:'D6119', description: "implant/abutment supported interim fixed denture for edentulous arch – maxillary", fee: 817.21},
    { code:'D6120', description: "implant supported retainer – porcelain fused to titanium and titanium alloys", fee: 401.53},
    { code:'D6121', description: "implant supported retainer for metal FPD – predominantly base alloys", fee: 224.51},
    { code:'D6122', description: "implant supported retainer for metal FPD – noble alloys", fee: 461.55},
    { code:'D6123', description: "implant supported retainer for metal FPD – titanium and titanium alloys", fee: 366.55},
    { code:'D6190', description: "radiographic/surgical implant index, by report", fee: 56.69},
    { code:'D6191', description: "semi-precision abutment – placement", fee: 920.82},
    { code:'D6192', description: "semi-precision attachment – placement", fee: 8.51},
    { code:'D6194', description: "abutment supported retainer crown for FPD – titanium and titanium alloys", fee: 498.92},
    { code:'D6195', description: "abutment supported retainer - porcelain fused to titanium and titanium alloys", fee: 245.96},
    { code:'D6199', description: "unspecified implant procedure, by report", fee: 400.18},
    { code:'D6205', description: "pontic - indirect resin based composite", fee: 650.02},
    { code:'D6210', description: "pontic - cast high noble metal", fee: 578.72},
    { code:'D6211', description: "pontic - cast predominantly base metal", fee: 10.53},
    { code:'D6212', description: "pontic - cast noble metal", fee: 100.07},
    { code:'D6214', description: "pontic - titanium and titanium alloys", fee: 883.30},
    { code:'D6240', description: "pontic - porcelain fused to high noble metal", fee: 367.04},
    { code:'D6241', description: "pontic - porcelain fused to predominantly base metal", fee: 644.36},
    { code:'D6242', description: "pontic - porcelain fused to noble metal", fee: 99.73},
    { code:'D6243', description: "pontic - porcelain fused to titanium and titanium alloys", fee: 586.41},
    { code:'D6245', description: "pontic - porcelain/ceramic", fee: 374.21},
    { code:'D6250', description: "pontic - resin with high noble metal", fee: 658.16},
    { code:'D6251', description: "pontic - resin with predominantly base metal", fee: 196.22},
    { code:'D6252', description: "pontic - resin with noble metal", fee: 32.95},
    { code:'D6253', description: "provisional pontic - further treatment or completion of diagnosis necessary prior to final  impression", fee: 928.59},
    { code:'D6545', description: "retainer - cast metal for resin bonded fixed prosthesis", fee: 433.93},
    { code:'D6548', description: "retainer - porcelain/ceramic for resin bonded fixed prosthesis", fee: 49.26},
    { code:'D6549', description: "retainer – for resin bonded fixed prosthesis", fee: 317.11},
    { code:'D6600', description: "retainer inlay - porcelain/ceramic, two surfaces", fee: 914.00},
    { code:'D6601', description: "retainer inlay - porcelain/ceramic, three or more surfaces", fee: 102.73},
    { code:'D6602', description: "retainer inlay - cast high noble metal, two surfaces", fee: 486.55},
    { code:'D6603', description: "retainer inlay - cast high noble metal, three or more surfaces", fee: 583.80},
    { code:'D6604', description: "retainer inlay - cast predominantly base metal, two surfaces", fee: 8.47},
    { code:'D6605', description: "retainer inlay - cast predominantly base metal, three or more surfaces", fee: 66.38},
    { code:'D6606', description: "retainer inlay - cast noble metal, two surfaces", fee: 769.43},
    { code:'D6607', description: "retainer inlay - cast noble metal, three or more surfaces", fee: 299.38},
    { code:'D6608', description: "retainer onlay - porcelain/ceramic, two surfaces", fee: 42.61},
    { code:'D6609', description: "retainer onlay - porcelain/ceramic, three or more surfaces", fee: 627.58},
    { code:'D6610', description: "retainer onlay - cast high noble metal, two surfaces", fee: 732.64},
    { code:'D6611', description: "retainer onlay - cast high noble metal, three or more surfaces", fee: 295.44},
    { code:'D6612', description: "retainer onlay - cast predominantly base metal, two surfaces", fee: 788.76},
    { code:'D6613', description: "retainer onlay - cast predominantly base metal, three or more surfaces", fee: 393.09},
    { code:'D6614', description: "retainer onlay - cast noble metal, two surfaces", fee: 232.87},
    { code:'D6615', description: "retainer onlay - cast noble metal, three or more surfaces", fee: 471.79},
    { code:'D6624', description: "retainer inlay - titanium", fee: 90.33},
    { code:'D6634', description: "retainer onlay - titanium", fee: 471.17},
    { code:'D6710', description: "retainer crown - indirect resin based composite", fee: 267.17},
    { code:'D6720', description: "retainer crown - resin with high noble metal", fee: 853.75},
    { code:'D6721', description: "retainer crown - resin with predominantly base metal", fee: 745.86},
    { code:'D6722', description: "retainer crown - resin with noble metal", fee: 997.11},
    { code:'D6740', description: "retainer crown - porcelain/ceramic", fee: 455.53},
    { code:'D6750', description: "retainer crown - porcelain fused to high noble metal", fee: 165.40},
    { code:'D6751', description: "retainer crown - porcelain fused to predominantly base metal", fee: 973.48},
    { code:'D6752', description: "retainer crown - porcelain fused to noble metal", fee: 189.66},
    { code:'D6753', description: "retainer crown - porcelain fused to titanium and titanium alloys", fee: 321.22},
    { code:'D6780', description: "retainer crown - 3/4 cast high noble metal", fee: 201.85},
    { code:'D6781', description: "retainer crown - 3/4 cast predominantly base metal", fee: 598.54},
    { code:'D6782', description: "retainer crown - 3/4 cast noble metal", fee: 966.28},
    { code:'D6783', description: "retainer crown - 3/4 porcelain/ceramic", fee: 947.68},
    { code:'D6784', description: "retainer crown ¾ - titanium and titanium alloys", fee: 62.45},
    { code:'D6790', description: "retainer crown - full cast high noble metal", fee: 331.22},
    { code:'D6791', description: "retainer crown - full cast predominantly base metal", fee: 126.75},
    { code:'D6792', description: "retainer crown - full cast noble metal", fee: 142.96},
    { code:'D6793', description: "provisional retainer crown - further treatment or completion of diagnosis necessary prior to final impression", fee: 740.96},
    { code:'D6794', description: "retainer crown - titanium and titanium alloys", fee: 630.48},
    { code:'D6920', description: "connector bar", fee: 252.13},
    { code:'D6930', description: "re-cement or re-bond fixed partial denture", fee: 200.38},
    { code:'D6940', description: "stress breaker", fee: 659.91},
    { code:'D6950', description: "precision attachment", fee: 687.01},
    { code:'D6980', description: "fixed partial denture repair necessitated by restorative material failure", fee: 760.28},
    { code:'D6985', description: "pediatric partial denture, fixed", fee: 708.37},
    { code:'D6999', description: "unspecified fixed prosthodontic procedure, by report", fee: 483.24},
    { code:'D7111', description: "extraction, coronal remnants – primary tooth", fee: 0.28},
    { code:'D7140', description: "extraction, erupted tooth or exposed root (elevation and/or forceps removal)", fee: 9.08},
    { code:'D7210', description: "extraction, erupted tooth requiring removal of bone and/or sectioning of tooth, and including elevation of mucoperiosteal flap if indicated", fee: 633.23},
    { code:'D7220', description: "removal of impacted tooth - soft tissue", fee: 944.63},
    { code:'D7230', description: "removal of impacted tooth - partially bony", fee: 873.10},
    { code:'D7240', description: "removal of impacted tooth - completely bony", fee: 945.17},
    { code:'D7241', description: "removal of impacted tooth - completely bony, with unusual surgical complications", fee: 74.89},
    { code:'D7250', description: "removal of residual tooth roots (cutting procedure)", fee: 488.62},
    { code:'D7251', description: "coronectomy – intentional partial tooth removal", fee: 902.47},
    { code:'D7260', description: "oroantral fistula closure", fee: 558.48},
    { code:'D7261', description: "primary closure of a sinus perforation", fee: 679.12},
    { code:'D7270', description: "tooth re-implantation and/or stabilization of accidentally evulsed or displaced tooth", fee: 237.33},
    { code:'D7272', description: "tooth transplantation (includes re-implantation from one site to another and splinting and/or stabilization)", fee: 206.25},
    { code:'D7280', description: "exposure of an unerupted tooth", fee: 322.12},
    { code:'D7282', description: "mobilization of erupted or malpositioned tooth to aid eruption", fee: 678.71},
    { code:'D7283', description: "placement of device to facilitate eruption of impacted tooth", fee: 167.68},
    { code:'D7285', description: "incisional biopsy of oral tissue-hard (bone, tooth)", fee: 692.62},
    { code:'D7286', description: "incisional biopsy of oral tissue-soft", fee: 871.91},
    { code:'D7287', description: "exfoliative cytological sample collection", fee: 931.72},
    { code:'D7288', description: "brush biopsy - transepithelial sample collection", fee: 412.38},
    { code:'D7290', description: "surgical repositioning of teeth", fee: 153.15},
    { code:'D7291', description: "transseptal fiberotomy/supra crestal fiberotomy, by report", fee: 411.75},
    { code:'D7292', description: "placement of temporary anchorage device [screw retained plate] requiring flap; includes device removal", fee: 126.53},
    { code:'D7293', description: "placement of temporary anchorage device requiring flap; includes device removal", fee: 282.54},
    { code:'D7294', description: "placement of temporary anchorage device without flap; includes device removal", fee: 339.93},
    { code:'D7295', description: "harvest of bone for use in autogenous grafting procedure", fee: 718.46},
    { code:'D7296', description: "corticotomy – one to three teeth or tooth spaces, per quadrant", fee: 531.68},
    { code:'D7297', description: "corticotomy – four or more teeth or tooth spaces, per quadrant", fee: 950.36},
    { code:'D7310', description: "alveoloplasty in conjunction with extractions - four or more teeth or tooth spaces, per quadrant", fee: 473.48},
    { code:'D7311', description: "alveoloplasty in conjunction with extractions - one to three teeth or tooth spaces, per quadrant", fee: 163.60},
    { code:'D7320', description: "alveoloplasty not in conjunction with extractions - four or more teeth or tooth spaces, per quadrant", fee: 282.50},
    { code:'D7321', description: "alveoloplasty not in conjunction with extractions - one to three teeth or tooth spaces, per quadrant", fee: 727.88},
    { code:'D7340', description: "vestibuloplasty - ridge extension (secondary epithelialization)", fee: 820.54},
    { code:'D7350', description: "vestibuloplasty - ridge extension (including soft tissue grafts, muscle reattachment, revision of soft tissue attachment and management of hypertrophied and hyperplastic tissue)", fee: 870.35},
    { code:'D7410', description: "excision of benign lesion up to 1.25 cm", fee: 217.11},
    { code:'D7411', description: "excision of benign lesion greater than 1.25 cm", fee: 530.51},
    { code:'D7412', description: "excision of benign lesion, complicated", fee: 79.30},
    { code:'D7413', description: "excision of malignant lesion up to 1.25 cm", fee: 979.50},
    { code:'D7414', description: "excision of malignant lesion greater than 1.25 cm", fee: 701.25},
    { code:'D7415', description: "excision of malignant lesion, complicated", fee: 424.11},
    { code:'D7440', description: "excision of malignant tumor - lesion diameter up to 1.25 cm", fee: 314.91},
    { code:'D7441', description: "excision of malignant tumor - lesion diameter greater than 1.25 cm", fee: 11.56},
    { code:'D7450', description: "removal of benign odontogenic cyst or tumor - lesion diameter up to 1.25 cm", fee: 714.23},
    { code:'D7451', description: "removal of benign odontogenic cyst or tumor - lesion diameter greater than 1.25 cm", fee: 120.06},
    { code:'D7460', description: "removal of benign nonodontogenic cyst or tumor - lesion diameter up to 1.25 cm", fee: 98.69},
    { code:'D7461', description: "removal of benign nonodontogenic cyst or tumor - lesion diameter greater than 1.25 cm", fee: 481.05},
    { code:'D7465', description: "destruction of lesion(s) by physical or chemical method, by report", fee: 707.63},
    { code:'D7471', description: "removal of lateral exostosis (maxilla or mandible)", fee: 904.59},
    { code:'D7472', description: "removal of torus palatinus", fee: 322.41},
    { code:'D7473', description: "removal of torus mandibularis", fee: 243.85},
    { code:'D7485', description: "reduction of osseous tuberosity", fee: 393.94},
    { code:'D7490', description: "radical resection of maxilla or mandible", fee: 767.48},
    { code:'D7510', description: "incision and drainage of abscess - intraoral soft tissue", fee: 882.16},
    { code:'D7511', description: "incision and drainage of abscess - intraoral soft tissue - complicated (includes drainage of multiple fascial spaces)", fee: 540.41},
    { code:'D7520', description: "incision and drainage of abscess - extraoral soft tissue", fee: 674.02},
    { code:'D7521', description: "incision and drainage of abscess - extraoral soft tissue - complicated (includes drainage of multiple fascial spaces)", fee: 429.15},
    { code:'D7530', description: "removal of foreign body from mucosa, skin, or subcutaneous alveolar tissue", fee: 56.57},
    { code:'D7540', description: "removal of reaction producing foreign bodies, musculoskeletal system", fee: 334.83},
    { code:'D7550', description: "partial ostectomy/sequestrectomy for removal of non-vital bone", fee: 370.16},
    { code:'D7560', description: "maxillary sinusotomy for removal of tooth fragment or foreign body", fee: 556.68},
    { code:'D7610', description: "maxilla - open reduction (teeth immobilized, if present)", fee: 940.03},
    { code:'D7620', description: "maxilla - closed reduction (teeth immobilized, if present)", fee: 344.24},
    { code:'D7630', description: "mandible - open reduction (teeth immobilized, if present)", fee: 296.10},
    { code:'D7640', description: "mandible - closed reduction (teeth immobilized, if present)", fee: 705.75},
    { code:'D7650', description: "malar and/or zygomatic arch - open reduction", fee: 734.12},
    { code:'D7660', description: "malar and/or zygomatic arch - closed reduction", fee: 102.61},
    { code:'D7670', description: "alveolus - closed reduction, may include stabilization of teeth", fee: 465.55},
    { code:'D7671', description: "alveolus - open reduction, may include stabilization of teeth", fee: 429.20},
    { code:'D7680', description: "facial bones - complicated reduction with fixation and multiple surgical approaches", fee: 48.99},
    { code:'D7710', description: "maxilla - open reduction", fee: 510.12},
    { code:'D7720', description: "maxilla - closed reduction", fee: 917.62},
    { code:'D7730', description: "mandible - open reduction", fee: 552.41},
    { code:'D7740', description: "mandible - closed reduction", fee: 621.26},
    { code:'D7750', description: "malar and/or zygomatic arch - open reduction", fee: 581.39},
    { code:'D7760', description: "malar and/or zygomatic arch - closed reduction", fee: 720.64},
    { code:'D7770', description: "alveolus - open reduction stabilization of teeth", fee: 831.36},
    { code:'D7771', description: "alveolus, closed reduction stabilization of teeth", fee: 16.32},
    { code:'D7780', description: "facial bones - complicated reduction with fixation and multiple approaches", fee: 525.10},
    { code:'D7810', description: "open reduction of dislocation", fee: 205.13},
    { code:'D7820', description: "closed reduction of dislocation", fee: 81.45},
    { code:'D7830', description: "manipulation under anesthesia", fee: 950.22},
    { code:'D7840', description: "condylectomy", fee: 862.80},
    { code:'D7850', description: "surgical discectomy, with/without implant", fee: 371.90},
    { code:'D7852', description: "disc repair", fee: 393.53},
    { code:'D7854', description: "synovectomy", fee: 839.76},
    { code:'D7856', description: "myotomy", fee: 25.83},
    { code:'D7858', description: "joint reconstruction", fee: 723.47},
    { code:'D7860', description: "arthrotomy", fee: 237.96},
    { code:'D7865', description: "arthroplasty", fee: 69.68},
    { code:'D7870', description: "arthrocentesis", fee: 757.28},
    { code:'D7871', description: "non-arthroscopic lysis and lavage", fee: 474.69},
    { code:'D7872', description: "arthroscopy - diagnosis, with or without biopsy", fee: 98.46},
    { code:'D7873', description: "arthroscopy: lavage and lysis of adhesions", fee: 251.62},
    { code:'D7874', description: "arthroscopy: disc repositioning and stabilization", fee: 689.82},
    { code:'D7875', description: "arthroscopy: synovectomy", fee: 212.65},
    { code:'D7876', description: "arthroscopy: discectomy", fee: 774.70},
    { code:'D7877', description: "arthroscopy: debridement", fee: 442.06},
    { code:'D7880', description: "occlusal orthotic device, by report", fee: 670.10},
    { code:'D7881', description: "occlusal orthotic device adjustment", fee: 596.87},
    { code:'D7899', description: "unspecified TMD therapy, by report", fee: 645.62},
    { code:'D7910', description: "suture of recent small wounds up to 5 cm", fee: 885.17},
    { code:'D7911', description: "complicated suture - up to 5 cm", fee: 757.45},
    { code:'D7912', description: "complicated suture - greater than 5 cm", fee: 617.00},
    { code:'D7920', description: "skin graft (identify defect covered, location and type of graft)", fee: 995.30},
    { code:'D7921', description: "collection and application of autologous blood concentrate product", fee: 351.10},
    { code:'D7922', description: "placement of intra-socket biological dressing to aid in hemostasis or clot stabilization, per site", fee: 336.65},
    { code:'D7940', description: "osteoplasty - for orthognathic deformities", fee: 258.73},
    { code:'D7941', description: "osteotomy - mandibular rami", fee: 968.84},
    { code:'D7943', description: "osteotomy - mandibular rami with bone graft; includes obtaining the graft", fee: 551.75},
    { code:'D7944', description: "osteotomy - segmented or subapical", fee: 454.11},
    { code:'D7945', description: "osteotomy - body of mandible", fee: 167.45},
    { code:'D7946', description: "LeFort I (maxilla - total)", fee: 847.92},
    { code:'D7947', description: "LeFort I (maxilla - segmented)", fee: 433.04},
    { code:'D7948', description: "LeFort II or LeFort III (osteoplasty of facial bones for midface hypoplasia or retrusion) - without bone graft", fee: 311.40},
    { code:'D7949', description: "LeFort II or LeFort III - with bone graft", fee: 45.16},
    { code:'D7950', description: "osseous, osteoperiosteal, or cartilage graft of the mandible or maxilla - autogenous or nonautogenous, by report", fee: 113.96},
    { code:'D7951', description: "sinus augmentation with bone or bone substitutes via a lateral open approach", fee: 366.76},
    { code:'D7952', description: "sinus augmentation via a vertical approach", fee: 832.11},
    { code:'D7953', description: "bone replacement graft for ridge preservation - per site", fee: 67.48},
    { code:'D7955', description: "repair of maxillofacial soft and/or hard tissue defect", fee: 201.29},
    { code:'D7960', description: "frenulectomy - also known as frenectomy or frenotomy - separate procedure not incidental to another procedure", fee: 394.53},
    { code:'D7961', description: "buccal / labial frenectomy (frenulectomy)", fee: 355.12},
    { code:'D7962', description: "lingual frenectomy (frenulectomy)", fee: 565.76},
    { code:'D7963', description: "frenuloplasty", fee: 933.79},
    { code:'D7970', description: "excision of hyperplastic tissue - per arch", fee: 712.91},
    { code:'D7971', description: "excision of pericoronal gingiva", fee: 801.87},
    { code:'D7972', description: "surgical reduction of fibrous tuberosity", fee: 583.81},
    { code:'D7979', description: "non – surgical sialolithotomy", fee: 385.25},
    { code:'D7980', description: "surgical sialolithotomy", fee: 530.78},
    { code:'D7981', description: "excision of salivary gland, by report", fee: 114.91},
    { code:'D7982', description: "sialodochoplasty", fee: 688.69},
    { code:'D7983', description: "closure of salivary fistula", fee: 307.26},
    { code:'D7990', description: "emergency tracheotomy", fee: 278.99},
    { code:'D7991', description: "coronoidectomy", fee: 371.89},
    { code:'D7993', description: "surgical placement of craniofacial implant – extra oral", fee: 592.41},
    { code:'D7994', description: "surgical placement: zygomatic implant", fee: 327.81},
    { code:'D7995', description: "synthetic graft - mandible or facial bones, by report", fee: 906.98},
    { code:'D7996', description: "implant-mandible for augmentation purposes (excluding alveolar ridge), by report", fee: 741.50},
    { code:'D7997', description: "appliance removal (not by dentist who placed appliance), includes removal of archbar", fee: 724.01},
    { code:'D7998', description: "intraoral placement of a fixation device not in conjunction with a fracture", fee: 839.81},
    { code:'D7999', description: "unspecified oral surgery procedure, by report", fee: 662.34},
    { code:'D8010', description: "limited orthodontic treatment of the primary dentition", fee: 367.06},
    { code:'D8020', description: "limited orthodontic treatment of the transitional dentition", fee: 880.67},
    { code:'D8030', description: "limited orthodontic treatment of the adolescent dentition", fee: 870.64},
    { code:'D8040', description: "limited orthodontic treatment of the adult dentition", fee: 316.46},
    { code:'D8050', description: "interceptive orthodontic treatment of the primary dentition", fee: 338.46},
    { code:'D8060', description: "interceptive orthodontic treatment of the transitional dentition", fee: 482.45},
    { code:'D8070', description: "comprehensive orthodontic treatment of the transitional dentition", fee: 252.14},
    { code:'D8080', description: "comprehensive orthodontic treatment of the adolescent dentition", fee: 273.45},
    { code:'D8090', description: "comprehensive orthodontic treatment of the adult dentition", fee: 144.84},
    { code:'D8210', description: "removable appliance therapy", fee: 756.52},
    { code:'D8220', description: "fixed appliance therapy", fee: 95.26},
    { code:'D8660', description: "pre-orthodontic treatment examination to monitor growth and development", fee: 378.78},
    { code:'D8670', description: "periodic orthodontic treatment visit", fee: 387.75},
    { code:'D8680', description: "orthodontic retention (removal of appliances, construction and placement of retainer(s))", fee: 385.09},
    { code:'D8681', description: "removable orthodontic retainer adjustment", fee: 914.17},
    { code:'D8690', description: "orthodontic treatment (alternative billing to a contract fee)", fee: 530.91},
    { code:'D8695', description: "removal of fixed orthodontic appliances for reasons other than completion of treatment", fee: 78.85},
    { code:'D8696', description: "repair of orthodontic appliance – maxillary", fee: 765.31},
    { code:'D8697', description: "repair of orthodontic appliance – mandibular", fee: 741.70},
    { code:'D8698', description: "re-cement or re-bond fixed retainer – maxillary", fee: 391.05},
    { code:'D8699', description: "re-cement or re-bond fixed retainer – mandibular", fee: 546.16},
    { code:'D8701', description: "repair of fixed retainer, includes reattachment – maxillary", fee: 50.06},
    { code:'D8702', description: "repair of fixed retainer, includes reattachment – mandibular", fee: 231.51},
    { code:'D8703', description: "replacement of lost or broken retainer – maxillary", fee: 584.96},
    { code:'D8704', description: "replacement of lost or broken retainer – mandibular", fee: 829.33},
    { code:'D8999', description: "unspecified orthodontic procedure, by report", fee: 565.16},
    { code:'D9110', description: "palliative (emergency) treatment of dental pain - minor procedure", fee: 51.82},
    { code:'D9120', description: "fixed partial denture sectioning", fee: 795.81},
    { code:'D9130', description: "temporomandibular joint dysfunction – non-invasive physical therapies", fee: 457.26},
    { code:'D9210', description: "local anesthesia not in conjunction with operative or surgical procedures", fee: 31.76},
    { code:'D9211', description: "regional block anesthesia", fee: 841.19},
    { code:'D9212', description: "trigeminal division block anesthesia", fee: 57.91},
    { code:'D9215', description: "local anesthesia in conjunction with operative or surgical procedures", fee: 670.12},
    { code:'D9219', description: "evaluation for moderate sedation, deep sedation or general anesthesia", fee: 261.60},
    { code:'D9222', description: "deep sedation/general anesthesia – first 15 minutes", fee: 619.34},
    { code:'D9223', description: "deep sedation/general anesthesia – each subsequent 15 minute increment", fee: 378.66},
    { code:'D9230', description: "inhalation of nitrous oxide/analgesia, anxiolysis", fee: 473.25},
    { code:'D9239', description: "intravenous moderate  (conscious) sedation/analgesia- first 15 minutes", fee: 638.66},
    { code:'D9243', description: "intravenous moderate (conscious) sedation/analgesia – each subsequent 15 minute increment", fee: 823.84},
    { code:'D9248', description: "non-intravenous conscious sedation", fee: 539.84},
    { code:'D9310', description: "consultation - diagnostic service provided by dentist or physician other than requesting dentist or physician", fee: 391.60},
    { code:'D9311', description: "consultation with a medical health care professional", fee: 752.32},
    { code:'D9410', description: "house/extended care facility call", fee: 78.45},
    { code:'D9420', description: "hospital or ambulatory surgical center call", fee: 558.95},
    { code:'D9430', description: "office visit for observation (during regularly scheduled hours) - no other services performed", fee: 431.37},
    { code:'D9440', description: "office visit - after regularly scheduled hours", fee: 5.15},
    { code:'D9450', description: "case presentation, detailed and extensive treatment planning", fee: 389.38},
    { code:'D9610', description: "therapeutic parenteral drug, single administration", fee: 827.69},
    { code:'D9612', description: "therapeutic parenteral drugs, two or more administrations, different medications", fee: 549.15},
    { code:'D9613', description: "infiltration of sustained release therapeutic drug – single or multiple sites", fee: 882.73},
    { code:'D9630', description: "drugs or medicaments dispensed in the office for home use", fee: 713.22},
    { code:'D9910', description: "application of desensitizing medicament", fee: 386.91},
    { code:'D9911', description: "application of desensitizing resin for cervical and/or root surface, per tooth", fee: 879.31},
    { code:'D9920', description: "behavior management, by report", fee: 843.50},
    { code:'D9930', description: "treatment of complications (post-surgical) - unusual circumstances, by report", fee: 743.10},
    { code:'D9932', description: "cleaning and inspection of removable complete denture, maxillary", fee: 146.12},
    { code:'D9933', description: "cleaning and inspection of removable complete denture, mandibular", fee: 76.67},
    { code:'D9934', description: "cleaning and inspection of removable partial denture, maxillary", fee: 463.17},
    { code:'D9935', description: "cleaning and inspection of removable partial denture, mandibular", fee: 319.73},
    { code:'D9941', description: "fabrication of athletic mouthguard", fee: 110.35},
    { code:'D9942', description: "repair and/or reline of occlusal guard", fee: 394.21},
    { code:'D9943', description: "occlusal guard adjustment", fee: 551.54},
    { code:'D9944', description: "occlusal guard – hard appliance, full arch", fee: 89.33},
    { code:'D9945', description: "occlusal guard – soft appliance, full arch", fee: 838.46},
    { code:'D9946', description: "occlusal guard – hard appliance, partial arch", fee: 534.66},
    { code:'D9950', description: "occlusion analysis - mounted case", fee: 448.54},
    { code:'D9951', description: "occlusal adjustment - limited", fee: 902.95},
    { code:'D9952', description: "occlusal adjustment - complete", fee: 424.31},
    { code:'D9961', description: "duplicate/copy patient's records", fee: 889.72},
    { code:'D9970', description: "enamel microabrasion", fee: 601.94},
    { code:'D9971', description: "odontoplasty - per tooth", fee: 979.59},
    { code:'D9972', description: "external bleaching - per arch - performed in office", fee: 265.83},
    { code:'D9973', description: "external bleaching - per tooth", fee: 512.46},
    { code:'D9974', description: "internal bleaching - per tooth", fee: 831.10},
    { code:'D9975', description: "external bleaching for home application, per arch; includes materials and fabrication of custom trays", fee: 40.47},
    { code:'D9985', description: "sales tax", fee: 766.90},
    { code:'D9986', description: "missed appointment", fee: 55.78},
    { code:'D9987', description: "cancelled appointment", fee: 388.73},
    { code:'D9990', description: "certified translation or sign-language services – per visit", fee: 462.36},
    { code:'D9991', description: "dental case management - addressing appointment compliance barriers", fee: 903.06},
    { code:'D9992', description: "dental case management - care coordination", fee: 954.10},
    { code:'D9993', description: "dental case management - motivational interviewing", fee: 47.30},
    { code:'D9994', description: "dental case management - patient education to improve oral health literacy", fee: 995.05},
    { code:'D9995', description: "teledentistry – synchronous; real-time encounter", fee: 274.66},
    { code:'D9996', description: "teledentistry – asynchronous; information stored and forwarded to dentist for subsequent review", fee: 325.40},
    { code:'D9997', description: "dental case management - patients with special health care needs", fee: 957.06},
    { code:'D9999', description: "unspecified adjunctive procedure, by report", fee: 741.44},];
  
  



  F11FormGroup: FormGroup;
  F21FormGroup: FormGroup;
  F31FormGroup: FormGroup;
  isEditable = true;

  ngOnInit(): void {
    this.F11FormGroup = this._formBuilder.group({
      firstNameCtrl: ['' ]
,             lastNameCtrl: ['' ]
,             miCtrl: ['']
,             suffixCtrl: ['']
   ,             akaCtrl: ['']
,             ssnCtrl: ['' ]
,             genderCtrl: ['' ]
,             dobCtrl: ['' ]
});
this.F21FormGroup = this._formBuilder.group({
      stateCtrl: ['' ]
,             numberCtrl: ['' ]
,             isActiveCtrl: ['' ]
   ,             isSpecialistCtrl: ['' ]
,             specialtyCtrl: ['']
,             subSpecialtyCtrl: ['']
   ,             yearsInPracticeCtrl: ['']
});
this.F31FormGroup = this._formBuilder.group({
      nameCtrl: ['' ]
,             stateCtrl: ['']
,             countryCtrl: ['' ]
   ,             degreeCtrl: ['' ]
});
}

}
